-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 22:32:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema concesionario_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concesionario_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concesionario_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `concesionario_db` ;

-- -----------------------------------------------------
-- Table `concesionario_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario_db`.`users` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NOT NULL DEFAULT 'imagen_default_usuario.jpg',
  `password` VARCHAR(255) NOT NULL,
  `terminos` VARCHAR(255) NOT NULL,
  `productcart_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `productcart_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `fk_users_productcart1_idx` (`productcart_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_productcart1`
    FOREIGN KEY (`productcart_id`)
    REFERENCES `concesionario_db`.`productcart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `concesionario_db`.`productcart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario_db`.`productcart` (
  `id` INT(11) NOT NULL,
  `name_user` VARCHAR(255) NOT NULL,
  `name_product` VARCHAR(255) NOT NULL,
  `totalPrice` INT(11) NOT NULL,
  `users_id` INT(11) NOT NULL,
  `products_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `products_id`),
  INDEX `fk_productcart_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_productcart_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_productcart_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `concesionario_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productcart_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `concesionario_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `concesionario_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario_db`.`products` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `marca` VARCHAR(255) NOT NULL,
  `modelo` VARCHAR(255) NOT NULL,
  `img1` VARCHAR(255) NOT NULL,
  `img2` VARCHAR(45) NOT NULL,
  `img3` VARCHAR(45) NOT NULL,
  `img4` VARCHAR(45) NOT NULL,
  `img5` VARCHAR(45) NOT NULL,
  `img6` VARCHAR(45) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `color` VARCHAR(255) NOT NULL,
  `price` INT(11) NOT NULL,
  `fichatecnica_id` INT(11) NOT NULL,
  `productcart_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `fichatecnica_id`, `productcart_id`),
  INDEX `fk_products_fichatecnica_idx` (`fichatecnica_id` ASC) VISIBLE,
  INDEX `fk_products_productcart1_idx` (`productcart_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_fichatecnica`
    FOREIGN KEY (`fichatecnica_id`)
    REFERENCES `concesionario_db`.`fichatecnica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_productcart1`
    FOREIGN KEY (`productcart_id`)
    REFERENCES `concesionario_db`.`productcart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `concesionario_db`.`fichatecnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario_db`.`fichatecnica` (
  `id` INT(11) NOT NULL,
  `motor` VARCHAR(255) NOT NULL,
  `potencia` TEXT NOT NULL,
  `torque` VARCHAR(255) NOT NULL,
  `transmision` VARCHAR(255) NOT NULL,
  `confort` VARCHAR(255) NOT NULL,
  `seguridad` VARCHAR(255) NOT NULL,
  `caracteristicas` VARCHAR(255) NOT NULL,
  `products_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `products_id`),
  INDEX `fk_fichatecnica_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_fichatecnica_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `concesionario_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
