-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 21:14:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema concesionario_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concesionario_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concesionario_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `concesionario_db` ;

-- -----------------------------------------------------
-- Table `concesionario_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario_db`.`products` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `marca` VARCHAR(255) NOT NULL,
  `modelo` VARCHAR(255) NOT NULL,
  `img` VARCHAR(2000) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(2000) NOT NULL,
  `caracteristicas` VARCHAR(2000) NOT NULL,
  `color` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `productcart_id` INT NOT NULL,
  PRIMARY KEY (`id`, `productcart_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `concesionario_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario_db`.`users` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NOT NULL DEFAULT 'imagen_default_usuario.jpg',
  `password` VARCHAR(255) NOT NULL,
  `terminos` VARCHAR(255) NOT NULL,
  `productcart_id` INT NOT NULL,
  PRIMARY KEY (`id`, `productcart_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `concesionario_db`.`productcart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario_db`.`productcart` (
  `id` INT NOT NULL,
  `name_user` VARCHAR(255) NOT NULL,
  `name_product` VARCHAR(255) NOT NULL,
  `totalPrice` INT NOT NULL,
  `users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `products_id`),
  INDEX `fk_productcart_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_productcart_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_productcart_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `concesionario_db`.`products` (`id`),
  CONSTRAINT `fk_productcart_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `concesionario_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
